paths:
  raw_morph: "data/raw/020625_PitLMorph.csv"
  raw_paleo: "data/raw/060625_paleoeco_seriesL.csv"
  raw_order: "data/raw/PitLMorph_fieldorder.csv"
  raw_missing_scales: "data/raw/Results_missingscales.txt"
  unassigned_functional_group: "data/review/unassigned_functional_group.csv"
  output_dir: "results"
  plot_dir: "results/plots"
  report_dir: "results/report"
  report_rmd: "report.Rmd"

analysis:
  conflict_threshold: 0.10
  rioja_grouping_level: "functional_groups" # "functional_groups" / "full_taxonomy"
  exclude_non_diagnostic: true  # Whether to apply exclusions
  community_evenness_index: "pielou"
  time_column: "CSTRAT"
  turnover_method: "bray"
  rare_taxa_threshold: 0.10
  community_trends_plot_type: "faceted"
  rioja_rare_taxa_threshold: 0.05

plots:
  completeness_width: 10
  completeness_height: 6
  microfossil_width: 10
  microfossil_height: 6
  community_trends_width: 10
  community_trends_height: 12
  turnover_heatmap_width: 10
  turnover_heatmap_height: 8
  turnover_color_palette: "viridis"
  recorder_bias_width: 10
  recorder_bias_height: 6

# Functional groupings for paleo-ecological analysis
functional_groupings:
  # Microfossils to exclude from analysis
  exclude_taxa:
    - microfossil_type: "Granules"
      patterns: ["*.*.*.*"]  # All Granules regardless of other taxonomy
  
  # Functional group definitions
  groups:
    "Woody dicotyledons":
      microfossil_type: "Phytolith"
      patterns: # Uses "." as a seperator (i.e. Morphotype.Genus_Type.Species.Variety) and "*" to denote "all"
        - "Elongate.Faceted.*.*"
        - "Polyhedral.Faceted.*.*"
        - "Polyhedral.Sclereid.*.*"
        - "Spheroid.Decorated.*.*"
        - "Tracheary_annulate.*.*.*"
    
    "Ferns, woody or herbaceous dicotyledons":
      microfossil_type: "Phytolith"
      patterns:
        - "Spheroid.Psilate.*.*"
        - "Spheroid.Faceted.*.*"
        - "Blocky.*.*.*"
        - "Spheroid.Ornate.*.*"
    
    "Grasses (Poaceae)":
      microfossil_type: "Phytolith"
      patterns:
        - "Bilobate.*.*.*"
        - "Crenate.*.*.*"
        - "Cross.*.*.*"
        - "Rondel.*.*.*"
        - "Saddle.*.*.*"
        - "Bulliform_flabellate.*.*.*"
    
    # Diatom groups
    "Araphid diatoms":
      microfossil_type: "Diatom"
      patterns: ["Araphid.*.*.*"]
    
    "Asymmetric Biraphid diatoms":
      microfossil_type: "Diatom"
      patterns: ["Asymmetric_Biraphid.*.*.*"]
    
    "Centric diatoms":
      microfossil_type: "Diatom"
      patterns: ["Centric.*.*.*"]
    
    "Epithemioid diatoms":
      microfossil_type: "Diatom"
      patterns: ["Epithemioid.*.*.*"]
    
    "Eunotioid diatoms":
      microfossil_type: "Diatom"
      patterns: ["Eunotioid.*.*.*"]
    
    "Monoraphid diatoms":
      microfossil_type: "Diatom"
      patterns: ["Monoraphid.*.*.*"]
    
    "Surirelloid diatoms":
      microfossil_type: "Diatom"
      patterns: ["Surirelloid.*.*.*"]
    
    "Symmetric Biraphid diatoms":
      microfossil_type: "Diatom"
      patterns: ["Symmetric_Biraphid.*.*.*"]
    
    "Nitzschioid diatoms":
      microfossil_type: "Diatom"
      patterns: ["Nitzschioid.*.*.*"]
    
    # Charred Group
    "Charred Remains":
      microfossil_type: "Charred"
      patterns: ["*.*.*.*"]
