# =============================================================================
# PROJECT CONFIGURATION FILE
# =============================================================================
# This YAML file defines all project-specific settings for the setup system.
# Modify this file to change project requirements without touching the setup code.

# Project metadata
project:
  name: "Fish Paleobiology Analysis"
  version: "2.1"
  description: "Integration of fish morphology and paleo-ecological data"
  author: "Aaron Myrold"

# Required R packages
packages:
  # Core data manipulation
  core:
    - dplyr
    - tidyr
    - stringr
    - tibble
    - purrr
  
  # Visualization and analysis
  visualization:
    - ggplot2
    - scales
  
  # Statistical and ecological analysis  
  statistics:
    - vegan
    - rioja
  
  # Optional packages (loaded if available, warnings if missing)
  optional:
    - readr
    - yaml

# Directory structure
folders:
  # Data folders
  - "data"
  - "data/raw"
  - "data/processed" 
  - "data/flagged"
  - "data/intermediate"
  
  # Code and functions
  - "src"
  - "scripts"
  
  # Results and outputs
  - "results"
  - "results/figures"
  - "results/figures/morphology"
  - "results/figures/paleoeco"
  - "results/figures/integrated"
  - "results/tables"
  - "results/reports"
  
  # Documentation
  - "docs"
  - "docs/logs"
  - "docs/metadata"
  - "docs/methods"
  
  # Environment
  - "env"

# Function files to load (in order)
functions:
  # Core infrastructure
  infrastructure:
    - "validation_functions.R"
  
  # Analysis-specific functions
  analysis:
    - "morph_cleaning.R"
    - "paleoeco_cleaning.R"
  
  # Optional function files (loaded if they exist)
  optional:
    - "visualization_functions.R"
    - "integration_functions.R"
    - "custom_analysis.R"

# Global R settings
settings:
  # Reproducibility
  seed: 333
  
  # R options
  r_options:
    stringsAsFactors: false
    scipen: 6
    digits: 4
  
  # Plot settings
  plot_defaults:
    width: 8
    height: 6
    dpi: 300

# Logging configuration
logging:
  enabled: true
  log_level: "INFO"
  auto_export: true
  output_dir: "4.docs/logs"

# Data file specifications (for validation)
data_files:
  required:
    - name: "020625_PitLMorph.csv"
      location: "1.data/a.raw"
      description: "Fish morphology measurements from objectJ"
    - name: "060625_paleoeco_seriesL.csv" 
      location: "1.data/a.raw"
      description: "Paleo-ecological microfossil counts"
    - name: "PitLMorph_fieldorder.csv"
      location: "1.data/a.raw"
      description: "Age and depth estimates"
  
  optional:
    - name: "additional_specimens.csv"
      location: "1.data/a.raw"
      description: "Supplementary morphology data"

# Analysis configurations
analysis:
  morphology:
    overlap_threshold: 0.05
    min_scale_required: true
    special_cases_enabled: true
  
  paleoeco:
    microfossil_types:
      - "Diatom"
      - "Phytolith"
    min_total_count: 5
    min_samples: 2
    include_killifish: true
    taxonomy_level: "morphotype"

# Environment validation rules
validation:
  r_version_min: "4.0.0"
  required_disk_space_mb: 100
  check_file_permissions: true
  validate_data_structure: true
